version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - mariadb.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network

  flask_app:
    image: flask_app:latest
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - flask_app.env
    volumes:
      - .:/usr/src/app
      - ./entrypoint.sh:/entrypoint.sh  
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      - mariadb
    entrypoint: ["/entrypoint.sh"]    

  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/flask_app.conf:/etc/nginx/conf.d/flask_app.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./nginx/certs:/etc/letsencrypt/live/flaskblog.chickenkiller.com/
      - ./nginx/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - ./nginx/entrypoint.sh:/entrypoint.sh
    networks:
      - my_network
    depends_on:
      - flask_app

networks:
  my_network:
    driver: bridge

volumes:
  mariadb_data:

